### ISSUE TITLE
US 1 - List of jokes

### ISSUE THREAD

**Issue by djfarly** [djfarly/capstone-jan#1]
## Value proposition

As an user
I want a see all jokes
So that i can remember my best jokes

## Description

- Scribble / design or text
- Precise, no unnecessary information

## Acceptance criteria

- [ ] all jokes are visible
- [ ] the viewport scroll if there are too many jokes
- [ ] …

## Tasks

- [ ] create a JokesList component

**Comment by djfarly** [comment]
Your AC are incomplete!
